<?xml version="1.0" encoding="utf-8"?>
<TestRun id="55d80ce3-460c-43e6-a1e4-b0e638a1ab27" name="@pkrvmbietmlfzoi 2025-07-08 19:35:14" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2025-07-08T19:35:14.9321599+00:00" queuing="2025-07-08T19:35:14.9321600+00:00" start="2025-07-08T19:35:11.3718917+00:00" finish="2025-07-08T19:35:14.9504824+00:00" />
  <TestSettings name="default" id="9feb5233-380b-4663-9a45-e7c29dd36208">
    <Deployment runDeploymentRoot="_pkrvmbietmlfzoi_2025-07-08_19_35_14" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="206faf0b-76ff-48bc-a76c-ef554d08bb46" testId="12bfb15c-b16f-387a-2b7a-dc6e12ebc0d0" testName="SuperSocket.Tests.ServerSentEventsTest.TestSSEHeartbeat(hostConfiguratorType: typeof(SuperSocket.Tests.RegularHostConfigurator))" computerName="pkrvmbietmlfzoi" duration="00:00:00.4314291" startTime="2025-07-08T19:35:14.1949846+00:00" endTime="2025-07-08T19:35:14.6541633+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="206faf0b-76ff-48bc-a76c-ef554d08bb46">
      <Output>
        <StdOut>The listener [Ip=Any, Port=4040, AuthenticationOptions=, Path=, BackLog=100, NoDelay=False] has been started.
Server started.
A new session connected: f17fc221-3b91-401e-ba3e-fca172468760
Heartbeat Response: HTTP/1.1 200 OK
Content-Type: text/event-stream
Cache-Control: no-cache
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Cache-Control
Date: Tue, 08 Jul 2025 19:35:14 GMT
Server: SuperSocket

: heartbeat

id: 1
event: test
retry: 3000
data: After heartbeat


The session disconnected: f17fc221-3b91-401e-ba3e-fca172468760 (RemoteClosing)
The listener[Ip=Any, Port=4040, AuthenticationOptions=, Path=, BackLog=100, NoDelay=False] was closed for the socket error: 125. Operation canceled
The listener [Ip=Any, Port=4040, AuthenticationOptions=, Path=, BackLog=100, NoDelay=False] has been stopped.</StdOut>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="SuperSocket.Tests.ServerSentEventsTest.TestSSEHeartbeat(hostConfiguratorType: typeof(SuperSocket.Tests.RegularHostConfigurator))" storage="/home/runner/work/supersocket/supersocket/test/supersocket.tests/bin/debug/net8.0/supersocket.tests.dll" id="12bfb15c-b16f-387a-2b7a-dc6e12ebc0d0">
      <Execution id="206faf0b-76ff-48bc-a76c-ef554d08bb46" />
      <TestMethod codeBase="/home/runner/work/SuperSocket/SuperSocket/test/SuperSocket.Tests/bin/Debug/net8.0/SuperSocket.Tests.dll" adapterTypeName="executor://xunit/VsTestRunner3/netcore/" className="SuperSocket.Tests.ServerSentEventsTest" name="TestSSEHeartbeat" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="12bfb15c-b16f-387a-2b7a-dc6e12ebc0d0" executionId="206faf0b-76ff-48bc-a76c-ef554d08bb46" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.01] xUnit.net VSTest Adapter v3.0.1+f8675c32e5 (64-bit .NET 8.0.17)
[xUnit.net 00:00:00.35]   Discovering: SuperSocket.Tests (app domain = off, method display = ClassAndMethod, method display options = None)
[xUnit.net 00:00:01.11]   Discovered:  SuperSocket.Tests (352 test cases to be run)
[xUnit.net 00:00:01.64]   Starting:    SuperSocket.Tests (parallel test collections = off, stop on fail = off, explicit = off, seed = 1819481313)
[xUnit.net 00:00:02.31]     SuperSocket.Tests.ServerSentEventsTest.TestSSEHeartbeat(hostConfiguratorType: typeof(SuperSocket.Tests.RegularHostConfigurator)) [PASS]
[xUnit.net 00:00:02.31]       Output:
[xUnit.net 00:00:02.31]         The listener [Ip=Any, Port=4040, AuthenticationOptions=, Path=, BackLog=100, NoDelay=False] has been started.
[xUnit.net 00:00:02.31]         Server started.
[xUnit.net 00:00:02.31]         A new session connected: f17fc221-3b91-401e-ba3e-fca172468760
[xUnit.net 00:00:02.31]         Heartbeat Response: HTTP/1.1 200 OK
[xUnit.net 00:00:02.31]         Content-Type: text/event-stream
[xUnit.net 00:00:02.31]         Cache-Control: no-cache
[xUnit.net 00:00:02.31]         Connection: keep-alive
[xUnit.net 00:00:02.31]         Access-Control-Allow-Origin: *
[xUnit.net 00:00:02.31]         Access-Control-Allow-Headers: Cache-Control
[xUnit.net 00:00:02.31]         Date: Tue, 08 Jul 2025 19:35:14 GMT
[xUnit.net 00:00:02.32]         Server: SuperSocket
[xUnit.net 00:00:02.32]         
[xUnit.net 00:00:02.32]         : heartbeat
[xUnit.net 00:00:02.32]         
[xUnit.net 00:00:02.32]         id: 1
[xUnit.net 00:00:02.32]         event: test
[xUnit.net 00:00:02.32]         retry: 3000
[xUnit.net 00:00:02.32]         data: After heartbeat
[xUnit.net 00:00:02.32]         
[xUnit.net 00:00:02.32]         
[xUnit.net 00:00:02.32]         The session disconnected: f17fc221-3b91-401e-ba3e-fca172468760 (RemoteClosing)
[xUnit.net 00:00:02.32]         The listener[Ip=Any, Port=4040, AuthenticationOptions=, Path=, BackLog=100, NoDelay=False] was closed for the socket error: 125. Operation canceled
[xUnit.net 00:00:02.32]         The listener [Ip=Any, Port=4040, AuthenticationOptions=, Path=, BackLog=100, NoDelay=False] has been stopped.
[xUnit.net 00:00:02.41]   Finished:    SuperSocket.Tests
</StdOut>
    </Output>
  </ResultSummary>
</TestRun>